# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  rss: /atom.xml
rss: atom.xml

menu_icon:
  Home: HOME
  Archives: ARCHIVES
  About: ABOUT
  rss: RSS

# Content
excerpt_link: つづき
fancybox: false

#your personal image
your_img: img/naosim.png

# Miscellaneous
google_analytics:
favicon:
twitter: naosim_
google_plus:
fb_admins:
fb_app_id:
