# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  rss: /atom.xml

menu_icon:
  Home: HOME
  Archives: ARCHIVES
  About: ABOUT
  rss: RSS

# Content
excerpt_link: Read More
fancybox: false

#your personal image
your_img: /blog/img/naosim.png

# Miscellaneous
google_analytics:
favicon:
twitter: naosim_
google_plus:
fb_admins:
fb_app_id:
